change order

diff --git a/.github/workflows/dbt_slim_ci.yml b/.github/workflows/dbt_slim_ci.yml
--- a/.github/workflows/dbt_slim_ci.yml
+++ b/.github/workflows/dbt_slim_ci.yml
@@ -56,27 +56,6 @@ jobs:
 
       - name: dbt dependencies
         run: "dbt deps"
-      
-      - name: Run dbt model on Trino if dunesql engine is used, and retry until cluster is available
-        if: matrix.engine == 'dunesql'
-        run: |
-          RETRY_COUNT=0
-          # max wait: 10 minutes
-          MAX_RETRIES=40
-          WAIT_TIME=15
-          
-          until [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]
-          do
-            dbt run $PROFILE --models trigger_scale && break
-            RETRY_COUNT=$((RETRY_COUNT+1))
-            if [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]; then
-              echo "Max retries reached, failing..."
-              exit 1
-            fi
-            echo "Retrying in $WAIT_TIME seconds... ($RETRY_COUNT/$MAX_RETRIES)"
-            sleep $WAIT_TIME
-          done
-
 
       - name: Check no common models between DuneSQL and Spark
         if: matrix.engine == 'dunesql'
@@ -106,6 +85,26 @@ jobs:
         run: |
           test=$(dbt --quiet --no-print ls $PROFILE --resource-type model --select tag:remove+ --exclude tag:remove --output path --state .)
           [[ -z "$test" ]] && { echo "Success"; exit 0; } || { echo "Found active child models of removed models:"; echo "$test"; exit 1; }
+
+      - name: Run dbt model on Trino if dunesql engine is used, and retry until cluster is available
+        if: matrix.engine == 'dunesql'
+        run: |
+          RETRY_COUNT=0
+          # max wait: 10 minutes
+          MAX_RETRIES=40
+          WAIT_TIME=15
+          
+          until [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]
+          do
+            dbt run $PROFILE --models trigger_scale && break
+            RETRY_COUNT=$((RETRY_COUNT+1))
+            if [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]; then
+              echo "Max retries reached, failing..."
+              exit 1
+            fi
+            echo "Retrying in $WAIT_TIME seconds... ($RETRY_COUNT/$MAX_RETRIES)"
+            sleep $WAIT_TIME
+          done
 
       - name: dbt seed
         run: "dbt seed $PROFILE --select state:modified$TAG --exclude tag:prod_exclude tag:remove --state ."
