Retry

diff --git a/.github/workflows/dbt_precommit_hooks.yml b/.github/workflows/dbt_precommit_hooks.yml
--- a/.github/workflows/dbt_precommit_hooks.yml
+++ b/.github/workflows/dbt_precommit_hooks.yml
@@ -37,7 +37,9 @@ jobs:
       - name: dbt compile
         run: "dbt compile"
       - name: check ref/source syntax
-        run: regex='^((?!--).)*from\s+[a-z0-9_]+\.+[a-z0-9_]+\]' && files=$(echo "$FILES" | grep ".sql$") && for f in $files; do lines=$(grep -E "$regex" $f); if [ ! -z "$lines" ]; then echo "File $f contains target string on lines:"; echo "$lines"; fi; done
+        run: |
+          test=$(regex='^((?!--).)*from\s+[a-z0-9_]+\.+[a-z0-9_]+\]' && files=$(echo "$FILES" | grep ".sql$") && for f in $files; do lines=$(grep -E "$regex" $f); if [ ! -z "$lines" ]; then echo "File $f contains target string on lines:"; echo "$lines"; fi; done)
+          [[ -z "$test" ]] && { echo "Success: No ref/source syntax errors found"; exit 0; } || { echo "Found ref/source syntax errors:"; echo "$test"; exit 1; }
       - name: check schemas
         run: |
           test=$(dbt --quiet --no-print ls --select config.schema:no_schema --output path)
