Add check ref/source syntax test in dbt_precommit_hooks

diff --git a/.github/workflows/dbt_precommit_hooks.yml b/.github/workflows/dbt_precommit_hooks.yml
--- a/.github/workflows/dbt_precommit_hooks.yml
+++ b/.github/workflows/dbt_precommit_hooks.yml
@@ -36,6 +36,18 @@ jobs:
         run: "dbt deps"
       - name: dbt compile
         run: "dbt compile"
+      - name: check ref/source syntax
+        run: |
+            regex='^((?!--).)*from\s+[a-z0-9_]+\.+[a-z0-9_]+'
+            files=$(echo "$FILES" | grep ".sql$")
+            for f in $files; do
+              lines=$(grep -E "$regex" $f)
+              if [ ! -z "$lines" ]; then
+                echo "File $f may have invalid ref/source syntax on lines:"
+                echo "$lines"
+                exit 1       
+              fi
+            done
       - name: check schemas
         run: |
           test=$(dbt --quiet --no-print ls --select config.schema:no_schema --output path)
